version: "1"
  sonarQube:
    image: sonarqube
    container_name: sonarQube
    environment: 
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports: 
      - "9000:9000"
    networks:
      - devops